name: Daily Plugin Snapshot

# 1) Grant this workflow write permissions for contents
permissions:
  contents: write

on:
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout with credentials
      - uses: actions/checkout@v3
        with:
          # persist the GITHUB_TOKEN so pushes succeed
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests tqdm

      - name: Run scraper
        env:
          # GITHUB_TOKEN here already has write on repo because of `permissions` above
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python fetch_stars_gql.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add plugin-details-*.csv
          git commit -m "Daily snapshot $(date +'%Y-%m-%d')" || echo "No changes"
          git push
